apiVersion: 1

datasources:
  - name: elasticsearch-clusters
    type: elasticsearch
    access: proxy
    database: "[.monitoring-es-6-]YYYY.MM.DD"
    url: http://elasticsearch-monitoring-es-http:9200
    jsonData:
      interval: Daily
      timeField: "timestamp"
      esVersion: 60
    editable: false
    isDefault: true
